vich_uploader:
    db_driver: orm
    metadata :
        type : attribute

    mappings:
        recipe_images:
            uri_prefix: /images/profilpictures
            upload_destination: '%kernel.project_dir%/public/images/profilpictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
